---
title: "Seed predation"
author: "Luis Antonio Arias Medellin"
date: "September 27, 2018"
output: html_document
---
```{r}
#Remove anything on workspace
#rm(list=ls(all=TRUE))

#Load libraries
library("openxlsx")

#Read file
seeds<-read.xlsx("Seed predation seedling survival experiemtents 2018.04.27.xlsx",sheet=5)

#Format date
seeds$Date<-as.Date(seeds$Date,origin="1899-12-30")

#See which years were the patches sampled
table(seeds$Site,substr(seeds$Date,1,4))

#The column seeds_germinated, the id of the seed was written separated by a comma or an N was placed when none of the seeds germinated. I will first change the N for a 0 to make the column 
table(seeds$Seeds_germinated)

#Make empty dat aframe with sites and trays (2 per site)
germination.data<-rbind(data.frame(Site=rep(unique(seeds$Site),times=1),tray=1),data.frame(Site=rep(unique(seeds$Site),times=1),tray=2))
germination.data$prop.germ<-NA

#The column seeds_germinated, the id of the seed was written separated by a comma or an N was placed when none of the seeds germinated. I will first change the N for a 0 to make the column 
seeds$Seeds_germinated<-ifelse(seeds$Seeds_germinated=="N",0,seeds$Seeds_germinated)

for (i in seeds$Site){
  #Subset site
  subset.site<-subset(seeds,seeds$Site==i)
  
  #The column seeds_germinated has the id of the seed that germinated but the numbers are separated by commas (i.e. 15,27). I will separate the id's
  germinated.seeds.id<-as.numeric(unique(unlist(strsplit(subset.site$Seeds_germinated,split=","))))
  
  #If no seeds germinated in any of the trays, then do a data frame with 0 germination so that I can add it to the data frame later
  if(sum(as.numeric(germinated.seeds.id))==0){ #If the sum  of the vector of seeds id is equal to 0, it means that there were no seeds germinating in any trays, so I will do a special data frame with 0's
  
    site.without.germination<-data.frame(Site=rep(unique(subset.site$Site),times=2),tray=1:2,prop.germ=0)
    
    #Merge with data base with germination information
    for (l in 1:nrow(site.without.germination)){
  germination.data$prop.germ<-ifelse(germination.data$Site==site.without.germination$Site[l] & germination.data$tray==site.without.germination$tray[l],site.without.germination$prop.germ[l],germination.data$prop.germ)
    
  }
    }else{
  
  #Subset seeds with id 0 since I think they mean no seeds germinated
  germinated.seeds.id<-germinated.seeds.id[germinated.seeds.id!="0"]
  
  #Do a data frame with the site and id of the germinated seed
  germinated.seeds.database<-data.frame(Site=rep(i,length.out=length(germinated.seeds.id)),id=as.numeric(germinated.seeds.id))
  
  #Since seeds with id 1-20 where in tray 1 and seeds with id 21-40 hwere in tray 2, I will us the seed id to label them in a tray id
  germinated.seeds.database$tray<-ifelse(germinated.seeds.database$id<=20,1,2)
  
  #Add a column with 1's to count the seeds that germinated
  germinated.seeds.database$counts<-1
  
  #Aggregate number of germinated seeds by site and tray
  germinated.seeds.database<-aggregate(germinated.seeds.database$counts,by=list(Site=germinated.seeds.database$Site,tray=germinated.seeds.database$tray),FUN=sum,na.rm=T)
  
  #Column names
  colnames(germinated.seeds.database)[3]<-"prop.germ"
  
  #Obtain the proportions of seeds germinated
  germinated.seeds.database$prop.germ<-germinated.seeds.database$prop.germ/20
  
  #Put the seed germination rate in the data frame
  for (l in 1:nrow(germinated.seeds.database)){
  germination.data$prop.germ<-ifelse(germination.data$Site==germinated.seeds.database$Site[l] & germination.data$tray==germinated.seeds.database$tray[l],germinated.seeds.database$prop.germ[l],germination.data$prop.germ)
  }
    }
  }

#Read excel data base of patch id, patch size and % forest
patches<-read.xlsx("Site_info_Costa_Rica.xlsx",sheet=1)

#Keep columns of interest
patches<-patches[,c(1,5,6,3)]

#Rename columns
colnames(patches)<-c("Site","percent_forest","elevation","patch_size")


#Merge areas with patch information data bases
germination.data<-merge(germination.data,patches,by="Site")

germination.data$prop.germ <- replace(germination.data$prop.germ,is.na(germination.data$prop.germ), 0)

rm(seeds,subset.site,germinated.seeds.id,patches)

```

```{r,echo=F}
#ANALYSIS OF GROWTH USING CANOPY OPENESS

#Obtain the canopy openess values from another script I made. Purl is used to obtain the code from an RMD file. If I run it, I need to go direclty to the ouput
library("knitr")
#purl("Canopy openess analysis.Rmd",output="Canopy openess analysis code.R")
#I HAVE TO ANALYZE DATA OF CANOPY OPENESS BY YEAR TO SEE IF THEY ARE DIFFERENCES
source("Canopy openess analysis code.R",local=T)

#I will remove data bases that I used in the source file but will not use here
rm(canopy,patches,agg.score)
```


```{r,echo=FALSE}

panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}


panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor * r)
}
```


```{r}
boxplot(germination.data$prop.germ)

germination.data<-merge(germination.data,agg.openess[,c("Patch","mean_openess")],by.x="Site",by.y="Patch",all=F)

germination.data$logpatch_size<-log(germination.data$patch_size)
pairs(germination.data[,c("prop.germ","logpatch_size","percent_forest","elevation","mean_openess")],lower.panel=panel.cor,diag.panel=panel.hist,panel=panel.smooth)
germination.data$prop.germ.transformed<-asin(sqrt(germination.data$prop.germ))

pairs(germination.data[,c("prop.germ.transformed","logpatch_size","percent_forest","elevation","mean_openess")],lower.panel=panel.cor,diag.panel=panel.hist,panel=panel.smooth)
```

```{r}
library("nlme")
#Model without random factor
summary(mod.1<-gls(prop.germ.transformed~logpatch_size+percent_forest+elevation + mean_openess,method = "REML", data = germination.data))

#GLMM nesting plot. I AM SUBSETING THE DATA THAT HAS NA
summary(mod.2<-lme(prop.germ.transformed~logpatch_size+percent_forest+elevation + mean_openess,random = ~1 | Site,data=germination.data,method="REML"))

#Took out percent of forest
summary(mod.3<-update(mod.2,.~. -logpatch_size))

#Took out elevation
summary(mod.4<-update(mod.3,.~. -elevation))

#Took out mean openness. MARGINALLY SIGNIFICANT
summary(mod.5<-update(mod.4,.~. -mean_openess))


AIC(mod.2,mod.3,mod.4,mod.5)
library("MuMIn")
Weights(AIC(mod.1,mod.2,mod.3,mod.4))

#Check assumptions of model
plot(mod.5)
residuals.model<-resid(mod.5)
plot(germination.data$mean_openess,residuals.model)

p1<-germination.data %>% 
  ggplot(aes(x=logpatch_size,y=prop.germ)) + 
  geom_point() + 
  geom_smooth(method="lm",colour="red") +
  xlab("Log patch size") +
  ylab("Probability of germination") +
  geom_text(x=6.7, y=0.45, label="a)",fontface="bold")

p2<-germination.data %>% 
  ggplot(aes(x=percent_forest,y=prop.germ)) + 
  geom_point() + 
  geom_smooth(method="lm",colour="red") +
  xlab("Percent of forest") +
  ylab("Probability of germination") +
  geom_text(x=70,y=0.45,label="b)",fontface="bold")

p3<-germination.data %>% 
  ggplot(aes(x=elevation,y=prop.germ)) + 
  geom_point() + 
  geom_smooth(method="lm",colour="red") +
  xlab("Elevation") +
  ylab("Probability of germination") +
  geom_text(x=1490, y=0.45, label="c)",fontface="bold")

p4<-germination.data %>% 
  ggplot(aes(x=mean_openess,y=prop.germ)) + 
  geom_point() + 
  geom_smooth(method="lm",colour="red") +
  xlab("Mean canopy openness (%)") +
  ylab("Probability of germination") +
  geom_text(x=19,y=0.45,label="d)",fontface="bold")

library("gridExtra")
p5<-grid.arrange(p1, p2,p3,p4, ncol=2)
ggsave("Graphs/seed germination vs variables.jpg",plot=p5)


rm(p1,p2,p3,p4,p5,germinated.seeds.database,i,residuals.model)
```
